### ISSUE TITLE
Use logging instead of STDOUT?

### ISSUE THREAD

**Issue by dotsdl** [jensengroup/propka-3.1#10]
I have written some analysis code that performs propka on every frame of a trajectory, and although it probably doesn't affect performance (much), it would be nice to be able to disable output to ``STDOUT`` so that my own progress indicators aren't drowned out by propka's output. This would probably be best implemented using the built-in ``logging`` module.

**Comment by orbeckst** [comment]
Addressed by PR #11 .

**Comment by matvey83** [comment]
With PR#12 (Replaces #11) we now have a functional --quiet option, that causes logging to stdout to be suppressed.   Is this sufficient to address this issue?

**Comment by orbeckst** [comment]
Very good!

**Comment by dotsdl** [comment]
Haven't tried it, but will close for now. Thanks!
