### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by deborahharrus** [jensengroup/propka-3.1#14]
Hey,
For some reasons the import completely fails under Windows environment. (see below)
Any idea how to fix this?

PyMOL>import propka
Traceback (most recent call last):
  File "C:\Program Files (x86)\PyMOL\PyMOL/modules\pymol\parser.py", line 260, in parse
    exec(layer.com2+"\n",self.pymol_names,self.pymol_names)
  File "<string>", line 1, in <module>
SyntaxError: future feature print_function is not defined (propka.py, line 119)

Thanks in advance!

**Comment by sobolevnrm** [comment]
I'm adding @speleo3 to this issue and closing it since it is PyMOL-specific.
