### ISSUE TITLE
Need stable release for Homebrew

### ISSUE THREAD

**Issue by YoshitakaMo** [jensengroup/propka-3.1#21]
Hi, 
I have made a homebrew formula of propka-3.1 for easy installation on macOS. I need a tagged stable release of this software since the homebrew has a versioning system. ( See also https://github.com/brewsci/homebrew-bio/pull/655 )

I will appreciate your help with this situation.

**Comment by sobolevnrm** [comment]
I've tagged 91925bb92092d3b180a9c086e81822a3fdec6939 as https://github.com/jensengroup/propka-3.1/releases/tag/v3.1.0
