### ISSUE TITLE
Problems with attributes

### ISSUE THREAD

**Issue by Abraham-HITS** [jensengroup/propka-3.1#25]
Dear Prof. Dr. Jensen,

I am having problems trying to use the propka library in python 3.6. The errors I get are related with the attributes. Please, find them in the next:
module 'propka' has no attribute 'calculations'
module 'propka' has no attribute 'protonate'
I think it is because in python 3.6 the syntax for importing modules has changed.
Have you tested this library in python 3.6 or higher? There is an updated version?

Best,
Abraham

**Comment by sobolevnrm** [comment]
The latest version of PROPKA (e.g., d7147799d815f6f273b4814419cd8d5955ad4569) has been tested with Python 3.6.
