### ISSUE TITLE
The URL links for the tutorial and the server are dead

### ISSUE THREAD

**Issue by bieniekmateusz** [jensengroup/propka-3.1#27]
"See propka.ki.ku.dk for the PROPKA web server, using the tutorial."

The tutorial references this: 
http://propka.ki.ku.dk/~luca/wiki/index.php/PROPKA_3.1_Tutorial

Possibly the tutorial could be uploaded to the repository? 

Thanks, Mat

**Comment by orbeckst** [comment]
I don't know anyone who still has access to the tutorials... .except the internet archive: Voila

https://web.archive.org/web/20120112172739/http://propka.ki.ku.dk/~luca/wiki/index.php/PROPKA_3.1_Tutorial

although images are missing and it mostly refers to the webserver.

**Comment by sobolevnrm** [comment]
I think we should close this unless @jhjensen2 can tell us where the tutorials live.

**Comment by jhjensen2** [comment]
They're long gone, so best to close the issue

**Comment by sobolevnrm** [comment]
Thanks, @jhjensen2
