### ISSUE TITLE
Merge duplicate tests in PROPKA 3.1

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka-3.1#34]
Are these tests really duplicates?
`python -m pytest` runs one test and it passes.
Running `python runtest.py` produces one failure:
```
RUNNING 1HPX-warn
 ERR:
 Failed to execute PROPKA on 1HPX-warn
 See: 1HPX-warn.out
```
```
propka31.py: error: unrecognized arguments: --quiet
```

_Originally posted by @speleo3 in https://github.com/jensengroup/propka-3.1/pull/30#issuecomment-629998692_

**Comment by sobolevnrm** [comment]
@speleo3 - I'd like to upgrade from unittest to pytest to fix this.  Any concerns?

**Comment by speleo3** [comment]
No concerns, I certainly like pytest better than unittest :-)
