### ISSUE TITLE
Propka3.1 installation failure 

### ISSUE THREAD

**Issue by Alejo1982** [jensengroup/propka-3.1#46]
I, guess, have installed propka, when I use it, I get the following error:

alejo@alejo:~/Desktop/Proyecto_UIS/Calculos/3NIR$ /home/alejo/.local/bin/propka31 3nir.pdb 
Traceback (most recent call last):
  File "/home/alejo/.local/bin/propka31", line 11, in <module>
    load_entry_point('PROPKA==3.1.1', 'console_scripts', 'propka31')()
  File "/home/alejo/.local/lib/python3.8/site-packages/PROPKA-3.1.1-py3.8.egg/propka/run.py", line 14, in main
TypeError: loadOptions() missing 1 required positional argument: 'args'

And I do not understand how to solve it,
Any suggestion?

Thank you in advance,
David

**Comment by sobolevnrm** [comment]
Hello.  I think I broke that with one of the recent updates; I will look for a solution.  In the meantime, you could go back to https://github.com/jensengroup/propka-3.1/commit/91925bb92092d3b180a9c086e81822a3fdec6939 for a temporary fix.  My apologies.

**Comment by Alejo1982** [comment]
Thank you for your fix!!!
:D

**Comment by DocKDE** [comment]
Hi, I have the same issue and your fix didn't help, I'm afraid.
